name: C# Application CI/Cd

on:
  workflow_call:
    inputs:
      project-path:
        type: string
        required: true
      tests-project-path:
        type: string
        required: false
        default: ''
      output-dir:
        type: string
        required: false
        default: output
      artifact-name:
        type: string
        required: false
        default: build-artifacts
      release-prefix:
        type: string
        required: false
        default: ${{ github.repository }}
      
jobs:
  build:
    name: Build
    runs-on: windows-2019
    outputs:
      version: ${{ steps.semver.outputs.version }}
      should-release: ${{ steps.semver.outputs.should-release }}
      is-prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
    steps:
      - id: semver
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          warnings-as-errors: true
      - name: Unit Tests
        if: ${{ inputs.tests-project-path != '' }}
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: ${{ inputs.tests-project-path }}
      - name: Publish
        uses: EasyDesk/action-dotnet-publish@v1
        with:
          output-dir: ${{ inputs.output-dir }}
          path: ${{ inputs.project-path }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.output-dir }}
  release:
    name: GitHub release
    runs-on: ubuntu-20.04
    needs: [build]
    if: needs.build.outputs.should-release == 'true'
    concurrency: release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
      - name: Zip build assets
        shell: bash
        env:
          ZIP_OUTPUT_NAME: ${{ inputs.release-prefix }}_${{ needs.build.outputs.version }}
        run: zip -r "${ZIP_OUTPUT_NAME//\//_}.zip" ./*
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.is-prerelease }}
          prefix: ${{ inputs.release-prefix }}
          files: |
            *.zip
  
  
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
        queries: security-and-quality
    - name: Setup .NET Core 3 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.x
    - name: Setup .NET 5 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Build sources
      uses: EasyDesk/action-dotnet-build@v1
      with:
        warnings-as-errors: true
        build-args: '/p:ContinuousIntegrationBuild=true /p:UseSharedCompilation=false'
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
