name: C# Application CI/Cd

on:
  workflow_call:
    inputs:
      project-path:
        type: string
        required: true
      output-dir:
        type: string
        required: false
        default: output
      artifact-name:
        type: string
        required: false
        default: build-artifacts
      release-prefix:
        type: string
        required: false
        default: ${{ github.repository }}
      
jobs:
  build:
    name: Build
    runs-on: windows-2019
    outputs:
      version: ${{ steps.semver.outputs.version }}
      should-release: ${{ steps.semver.outputs.should-release }}
      is-prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
    steps:
      - id: semver
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          warnings-as-errors: true
      - name: Publish
        uses: EasyDesk/action-dotnet-publish@v1
        with:
          output-dir: ${{ inputs.output-dir }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.output-dir }}
  release:
    name: GitHub release
    runs-on: ubuntu-20.04
    needs: [build]
    if: needs.build.outputs.should-release == 'true'
    concurrency: release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
      - name: Zip build assets
        shell: bash
        env:
          ZIP_OUTPUT_NAME: ${{ inputs.release-prefix }}_${{ needs.build.outputs.version }}
        run: zip -r "${ZIP_OUTPUT_NAME//\//_}.zip" '${{ inputs.output-dir }}'/*
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.is-prerelease }}
          prefix: ${{ inputs.release-prefix }}
          files: |
            *.zip
